/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees.$employeeId'
import { Route as EmployeesAttendanceRouteImport } from './routes/employees.attendance'
import { Route as EmployeesDocumentsRouteImport } from './routes/employees.documents'
import { Route as EmployeesLeaveRouteImport } from './routes/employees.leave'
import { Route as EmployeesPayrollRouteImport } from './routes/employees.payroll'
import { Route as EmployeesPerformanceRouteImport } from './routes/employees.performance'
import { Route as EmployeesSettingsRouteImport } from './routes/employees.settings'
import { Route as EmployeesTimesheetsRouteImport } from './routes/employees.timesheets'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesAttendanceRoute = EmployeesAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesDocumentsRoute = EmployeesDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesLeaveRoute = EmployeesLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesPayrollRoute = EmployeesPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesPerformanceRoute = EmployeesPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesSettingsRoute = EmployeesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesTimesheetsRoute = EmployeesTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => EmployeesRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/finance': typeof FinanceRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/leave': typeof EmployeesLeaveRoute
  '/employees/payroll': typeof EmployeesPayrollRoute
  '/employees/performance': typeof EmployeesPerformanceRoute
  '/employees/settings': typeof EmployeesSettingsRoute
  '/employees/timesheets': typeof EmployeesTimesheetsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/finance': typeof FinanceRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/leave': typeof EmployeesLeaveRoute
  '/employees/payroll': typeof EmployeesPayrollRoute
  '/employees/performance': typeof EmployeesPerformanceRoute
  '/employees/settings': typeof EmployeesSettingsRoute
  '/employees/timesheets': typeof EmployeesTimesheetsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/employees': typeof EmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/finance': typeof FinanceRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/leave': typeof EmployeesLeaveRoute
  '/employees/payroll': typeof EmployeesPayrollRoute
  '/employees/performance': typeof EmployeesPerformanceRoute
  '/employees/settings': typeof EmployeesSettingsRoute
  '/employees/timesheets': typeof EmployeesTimesheetsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/clients'
    | '/employees'
    | '/finance'
    | '/inbox'
    | '/leads'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/employees/attendance'
    | '/employees/documents'
    | '/employees/leave'
    | '/employees/payroll'
    | '/employees/performance'
    | '/employees/settings'
    | '/employees/timesheets'
    | '/projects/$projectId'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/clients'
    | '/finance'
    | '/inbox'
    | '/leads'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/employees/attendance'
    | '/employees/documents'
    | '/employees/leave'
    | '/employees/payroll'
    | '/employees/performance'
    | '/employees/settings'
    | '/employees/timesheets'
    | '/projects/$projectId'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/clients'
    | '/employees'
    | '/finance'
    | '/inbox'
    | '/leads'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/employees/attendance'
    | '/employees/documents'
    | '/employees/leave'
    | '/employees/payroll'
    | '/employees/performance'
    | '/employees/settings'
    | '/employees/timesheets'
    | '/projects/$projectId'
    | '/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  EmployeesRoute: typeof EmployeesRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  InboxRoute: typeof InboxRoute
  LeadsRoute: typeof LeadsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/attendance': {
      id: '/employees/attendance'
      path: '/attendance'
      fullPath: '/employees/attendance'
      preLoaderRoute: typeof EmployeesAttendanceRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/documents': {
      id: '/employees/documents'
      path: '/documents'
      fullPath: '/employees/documents'
      preLoaderRoute: typeof EmployeesDocumentsRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/leave': {
      id: '/employees/leave'
      path: '/leave'
      fullPath: '/employees/leave'
      preLoaderRoute: typeof EmployeesLeaveRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/payroll': {
      id: '/employees/payroll'
      path: '/payroll'
      fullPath: '/employees/payroll'
      preLoaderRoute: typeof EmployeesPayrollRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/performance': {
      id: '/employees/performance'
      path: '/performance'
      fullPath: '/employees/performance'
      preLoaderRoute: typeof EmployeesPerformanceRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/settings': {
      id: '/employees/settings'
      path: '/settings'
      fullPath: '/employees/settings'
      preLoaderRoute: typeof EmployeesSettingsRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/timesheets': {
      id: '/employees/timesheets'
      path: '/timesheets'
      fullPath: '/employees/timesheets'
      preLoaderRoute: typeof EmployeesTimesheetsRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface EmployeesRouteChildren {
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesAttendanceRoute: typeof EmployeesAttendanceRoute
  EmployeesDocumentsRoute: typeof EmployeesDocumentsRoute
  EmployeesLeaveRoute: typeof EmployeesLeaveRoute
  EmployeesPayrollRoute: typeof EmployeesPayrollRoute
  EmployeesPerformanceRoute: typeof EmployeesPerformanceRoute
  EmployeesSettingsRoute: typeof EmployeesSettingsRoute
  EmployeesTimesheetsRoute: typeof EmployeesTimesheetsRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesAttendanceRoute: EmployeesAttendanceRoute,
  EmployeesDocumentsRoute: EmployeesDocumentsRoute,
  EmployeesLeaveRoute: EmployeesLeaveRoute,
  EmployeesPayrollRoute: EmployeesPayrollRoute,
  EmployeesPerformanceRoute: EmployeesPerformanceRoute,
  EmployeesSettingsRoute: EmployeesSettingsRoute,
  EmployeesTimesheetsRoute: EmployeesTimesheetsRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  ClientsRoute: ClientsRouteWithChildren,
  EmployeesRoute: EmployeesRouteWithChildren,
  FinanceRoute: FinanceRoute,
  InboxRoute: InboxRoute,
  LeadsRoute: LeadsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
