/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './frontend/routes/__root'
import { Route as IndexRouteImport } from './frontend/routes/index'
import { Route as AssetsRouteImport } from './frontend/routes/assets'
import { Route as ClientsRouteImport } from './frontend/routes/clients'
import { Route as EmployeesRouteImport } from './frontend/routes/employees'
import { Route as FinanceRouteImport } from './frontend/routes/finance'
import { Route as ForgotPasswordRouteImport } from './frontend/routes/forgot-password'
import { Route as InboxRouteImport } from './frontend/routes/inbox'
import { Route as LeadsRouteImport } from './frontend/routes/leads'
import { Route as LoginRouteImport } from './frontend/routes/login'
import { Route as OperationsRouteImport } from './frontend/routes/operations'
import { Route as ProjectsRouteImport } from './frontend/routes/projects'
import { Route as ReportsRouteImport } from './frontend/routes/reports'
import { Route as ResetPasswordRouteImport } from './frontend/routes/reset-password'
import { Route as SettingsRouteImport } from './frontend/routes/settings'
import { Route as TasksRouteImport } from './frontend/routes/tasks'
import { Route as VerifyEmailRouteImport } from './frontend/routes/verify-email'
import { Route as ClientsIndexRouteImport } from './frontend/routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './frontend/routes/clients.$clientId'
import { Route as EmployeesIndexRouteImport } from './frontend/routes/employees.index'
import { Route as EmployeesEmployeeIdRouteImport } from './frontend/routes/employees.$employeeId'
import { Route as EmployeesAttendanceRouteImport } from './frontend/routes/employees.attendance'
import { Route as EmployeesDocumentsRouteImport } from './frontend/routes/employees.documents'
import { Route as EmployeesLeaveRouteImport } from './frontend/routes/employees.leave'
import { Route as EmployeesPayrollRouteImport } from './frontend/routes/employees.payroll'
import { Route as EmployeesPerformanceRouteImport } from './frontend/routes/employees.performance'
import { Route as EmployeesSettingsRouteImport } from './frontend/routes/employees.settings'
import { Route as EmployeesTimesheetsRouteImport } from './frontend/routes/employees.timesheets'
import { Route as FinanceIndexRouteImport } from './frontend/routes/finance.index'
import { Route as FinanceExpensesRouteImport } from './frontend/routes/finance.expenses'
import { Route as FinanceInvoicesRouteImport } from './frontend/routes/finance.invoices'
import { Route as FinancePaymentsRouteImport } from './frontend/routes/finance.payments'
import { Route as InboxIndexRouteImport } from './frontend/routes/inbox.index'
import { Route as InboxNotificationsRouteImport } from './frontend/routes/inbox.notifications'
import { Route as LeadsIndexRouteImport } from './frontend/routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './frontend/routes/leads.$leadId'
import { Route as OperationsIndexRouteImport } from './frontend/routes/operations.index'
import { Route as OperationsClientsRouteImport } from './frontend/routes/operations.clients'
import { Route as OperationsDeliverablesRouteImport } from './frontend/routes/operations.deliverables'
import { Route as OperationsWorkloadRouteImport } from './frontend/routes/operations.workload'
import { Route as ProjectsIndexRouteImport } from './frontend/routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './frontend/routes/projects.$projectId'
import { Route as ReportsIndexRouteImport } from './frontend/routes/reports.index'
import { Route as ReportsEmployeesRouteImport } from './frontend/routes/reports.employees'
import { Route as ReportsFinanceRouteImport } from './frontend/routes/reports.finance'
import { Route as ReportsLeadsRouteImport } from './frontend/routes/reports.leads'
import { Route as ReportsProjectsRouteImport } from './frontend/routes/reports.projects'
import { Route as SettingsIndexRouteImport } from './frontend/routes/settings.index'
import { Route as SettingsClientPackagesRouteImport } from './frontend/routes/settings.client-packages'
import { Route as SettingsIntegrationsRouteImport } from './frontend/routes/settings.integrations'
import { Route as SettingsNotificationsRouteImport } from './frontend/routes/settings.notifications'
import { Route as SettingsRolesRouteImport } from './frontend/routes/settings.roles'
import { Route as SettingsWorkflowsRouteImport } from './frontend/routes/settings.workflows'
import { Route as TasksIndexRouteImport } from './frontend/routes/tasks.index'
import { Route as TasksBoardRouteImport } from './frontend/routes/tasks.board'
import { Route as TasksCalendarRouteImport } from './frontend/routes/tasks.calendar'
import { Route as TasksListRouteImport } from './frontend/routes/tasks.list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesAttendanceRoute = EmployeesAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesDocumentsRoute = EmployeesDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesLeaveRoute = EmployeesLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesPayrollRoute = EmployeesPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesPerformanceRoute = EmployeesPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesSettingsRoute = EmployeesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesTimesheetsRoute = EmployeesTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => EmployeesRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => FinanceRoute,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const InboxNotificationsRoute = InboxNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => InboxRoute,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsClientsRoute = OperationsClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsDeliverablesRoute = OperationsDeliverablesRouteImport.update({
  id: '/deliverables',
  path: '/deliverables',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsWorkloadRoute = OperationsWorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => OperationsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsEmployeesRoute = ReportsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsFinanceRoute = ReportsFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsLeadsRoute = ReportsLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsProjectsRoute = ReportsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ReportsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsClientPackagesRoute = SettingsClientPackagesRouteImport.update({
  id: '/client-packages',
  path: '/client-packages',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWorkflowsRoute = SettingsWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => SettingsRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksBoardRoute = TasksBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => TasksRoute,
} as any)
const TasksCalendarRoute = TasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TasksRoute,
} as any)
const TasksListRoute = TasksListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/leave': typeof EmployeesLeaveRoute
  '/employees/payroll': typeof EmployeesPayrollRoute
  '/employees/performance': typeof EmployeesPerformanceRoute
  '/employees/settings': typeof EmployeesSettingsRoute
  '/employees/timesheets': typeof EmployeesTimesheetsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inbox/notifications': typeof InboxNotificationsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/operations/clients': typeof OperationsClientsRoute
  '/operations/deliverables': typeof OperationsDeliverablesRoute
  '/operations/workload': typeof OperationsWorkloadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/employees': typeof ReportsEmployeesRoute
  '/reports/finance': typeof ReportsFinanceRoute
  '/reports/leads': typeof ReportsLeadsRoute
  '/reports/projects': typeof ReportsProjectsRoute
  '/settings/client-packages': typeof SettingsClientPackagesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/workflows': typeof SettingsWorkflowsRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/list': typeof TasksListRoute
  '/clients/': typeof ClientsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/leave': typeof EmployeesLeaveRoute
  '/employees/payroll': typeof EmployeesPayrollRoute
  '/employees/performance': typeof EmployeesPerformanceRoute
  '/employees/settings': typeof EmployeesSettingsRoute
  '/employees/timesheets': typeof EmployeesTimesheetsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inbox/notifications': typeof InboxNotificationsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/operations/clients': typeof OperationsClientsRoute
  '/operations/deliverables': typeof OperationsDeliverablesRoute
  '/operations/workload': typeof OperationsWorkloadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/employees': typeof ReportsEmployeesRoute
  '/reports/finance': typeof ReportsFinanceRoute
  '/reports/leads': typeof ReportsLeadsRoute
  '/reports/projects': typeof ReportsProjectsRoute
  '/settings/client-packages': typeof SettingsClientPackagesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/workflows': typeof SettingsWorkflowsRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/list': typeof TasksListRoute
  '/clients': typeof ClientsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/employees': typeof EmployeesRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/attendance': typeof EmployeesAttendanceRoute
  '/employees/documents': typeof EmployeesDocumentsRoute
  '/employees/leave': typeof EmployeesLeaveRoute
  '/employees/payroll': typeof EmployeesPayrollRoute
  '/employees/performance': typeof EmployeesPerformanceRoute
  '/employees/settings': typeof EmployeesSettingsRoute
  '/employees/timesheets': typeof EmployeesTimesheetsRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inbox/notifications': typeof InboxNotificationsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/operations/clients': typeof OperationsClientsRoute
  '/operations/deliverables': typeof OperationsDeliverablesRoute
  '/operations/workload': typeof OperationsWorkloadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/employees': typeof ReportsEmployeesRoute
  '/reports/finance': typeof ReportsFinanceRoute
  '/reports/leads': typeof ReportsLeadsRoute
  '/reports/projects': typeof ReportsProjectsRoute
  '/settings/client-packages': typeof SettingsClientPackagesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/workflows': typeof SettingsWorkflowsRoute
  '/tasks/board': typeof TasksBoardRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/list': typeof TasksListRoute
  '/clients/': typeof ClientsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/clients'
    | '/employees'
    | '/finance'
    | '/forgot-password'
    | '/inbox'
    | '/leads'
    | '/login'
    | '/operations'
    | '/projects'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/tasks'
    | '/verify-email'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/employees/attendance'
    | '/employees/documents'
    | '/employees/leave'
    | '/employees/payroll'
    | '/employees/performance'
    | '/employees/settings'
    | '/employees/timesheets'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inbox/notifications'
    | '/leads/$leadId'
    | '/operations/clients'
    | '/operations/deliverables'
    | '/operations/workload'
    | '/projects/$projectId'
    | '/reports/employees'
    | '/reports/finance'
    | '/reports/leads'
    | '/reports/projects'
    | '/settings/client-packages'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/workflows'
    | '/tasks/board'
    | '/tasks/calendar'
    | '/tasks/list'
    | '/clients/'
    | '/employees/'
    | '/finance/'
    | '/inbox/'
    | '/leads/'
    | '/operations/'
    | '/projects/'
    | '/reports/'
    | '/settings/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/employees/attendance'
    | '/employees/documents'
    | '/employees/leave'
    | '/employees/payroll'
    | '/employees/performance'
    | '/employees/settings'
    | '/employees/timesheets'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inbox/notifications'
    | '/leads/$leadId'
    | '/operations/clients'
    | '/operations/deliverables'
    | '/operations/workload'
    | '/projects/$projectId'
    | '/reports/employees'
    | '/reports/finance'
    | '/reports/leads'
    | '/reports/projects'
    | '/settings/client-packages'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/workflows'
    | '/tasks/board'
    | '/tasks/calendar'
    | '/tasks/list'
    | '/clients'
    | '/employees'
    | '/finance'
    | '/inbox'
    | '/leads'
    | '/operations'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/clients'
    | '/employees'
    | '/finance'
    | '/forgot-password'
    | '/inbox'
    | '/leads'
    | '/login'
    | '/operations'
    | '/projects'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/tasks'
    | '/verify-email'
    | '/clients/$clientId'
    | '/employees/$employeeId'
    | '/employees/attendance'
    | '/employees/documents'
    | '/employees/leave'
    | '/employees/payroll'
    | '/employees/performance'
    | '/employees/settings'
    | '/employees/timesheets'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inbox/notifications'
    | '/leads/$leadId'
    | '/operations/clients'
    | '/operations/deliverables'
    | '/operations/workload'
    | '/projects/$projectId'
    | '/reports/employees'
    | '/reports/finance'
    | '/reports/leads'
    | '/reports/projects'
    | '/settings/client-packages'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/workflows'
    | '/tasks/board'
    | '/tasks/calendar'
    | '/tasks/list'
    | '/clients/'
    | '/employees/'
    | '/finance/'
    | '/inbox/'
    | '/leads/'
    | '/operations/'
    | '/projects/'
    | '/reports/'
    | '/settings/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  EmployeesRoute: typeof EmployeesRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InboxRoute: typeof InboxRouteWithChildren
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/attendance': {
      id: '/employees/attendance'
      path: '/attendance'
      fullPath: '/employees/attendance'
      preLoaderRoute: typeof EmployeesAttendanceRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/documents': {
      id: '/employees/documents'
      path: '/documents'
      fullPath: '/employees/documents'
      preLoaderRoute: typeof EmployeesDocumentsRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/leave': {
      id: '/employees/leave'
      path: '/leave'
      fullPath: '/employees/leave'
      preLoaderRoute: typeof EmployeesLeaveRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/payroll': {
      id: '/employees/payroll'
      path: '/payroll'
      fullPath: '/employees/payroll'
      preLoaderRoute: typeof EmployeesPayrollRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/performance': {
      id: '/employees/performance'
      path: '/performance'
      fullPath: '/employees/performance'
      preLoaderRoute: typeof EmployeesPerformanceRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/settings': {
      id: '/employees/settings'
      path: '/settings'
      fullPath: '/employees/settings'
      preLoaderRoute: typeof EmployeesSettingsRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/timesheets': {
      id: '/employees/timesheets'
      path: '/timesheets'
      fullPath: '/employees/timesheets'
      preLoaderRoute: typeof EmployeesTimesheetsRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/invoices': {
      id: '/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/inbox/notifications': {
      id: '/inbox/notifications'
      path: '/notifications'
      fullPath: '/inbox/notifications'
      preLoaderRoute: typeof InboxNotificationsRouteImport
      parentRoute: typeof InboxRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/clients': {
      id: '/operations/clients'
      path: '/clients'
      fullPath: '/operations/clients'
      preLoaderRoute: typeof OperationsClientsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/deliverables': {
      id: '/operations/deliverables'
      path: '/deliverables'
      fullPath: '/operations/deliverables'
      preLoaderRoute: typeof OperationsDeliverablesRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/workload': {
      id: '/operations/workload'
      path: '/workload'
      fullPath: '/operations/workload'
      preLoaderRoute: typeof OperationsWorkloadRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/employees': {
      id: '/reports/employees'
      path: '/employees'
      fullPath: '/reports/employees'
      preLoaderRoute: typeof ReportsEmployeesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/finance': {
      id: '/reports/finance'
      path: '/finance'
      fullPath: '/reports/finance'
      preLoaderRoute: typeof ReportsFinanceRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/leads': {
      id: '/reports/leads'
      path: '/leads'
      fullPath: '/reports/leads'
      preLoaderRoute: typeof ReportsLeadsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/projects': {
      id: '/reports/projects'
      path: '/projects'
      fullPath: '/reports/projects'
      preLoaderRoute: typeof ReportsProjectsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/client-packages': {
      id: '/settings/client-packages'
      path: '/client-packages'
      fullPath: '/settings/client-packages'
      preLoaderRoute: typeof SettingsClientPackagesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/workflows': {
      id: '/settings/workflows'
      path: '/workflows'
      fullPath: '/settings/workflows'
      preLoaderRoute: typeof SettingsWorkflowsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/board': {
      id: '/tasks/board'
      path: '/board'
      fullPath: '/tasks/board'
      preLoaderRoute: typeof TasksBoardRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/calendar': {
      id: '/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof TasksCalendarRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/list': {
      id: '/tasks/list'
      path: '/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof TasksListRouteImport
      parentRoute: typeof TasksRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface EmployeesRouteChildren {
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesAttendanceRoute: typeof EmployeesAttendanceRoute
  EmployeesDocumentsRoute: typeof EmployeesDocumentsRoute
  EmployeesLeaveRoute: typeof EmployeesLeaveRoute
  EmployeesPayrollRoute: typeof EmployeesPayrollRoute
  EmployeesPerformanceRoute: typeof EmployeesPerformanceRoute
  EmployeesSettingsRoute: typeof EmployeesSettingsRoute
  EmployeesTimesheetsRoute: typeof EmployeesTimesheetsRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesAttendanceRoute: EmployeesAttendanceRoute,
  EmployeesDocumentsRoute: EmployeesDocumentsRoute,
  EmployeesLeaveRoute: EmployeesLeaveRoute,
  EmployeesPayrollRoute: EmployeesPayrollRoute,
  EmployeesPerformanceRoute: EmployeesPerformanceRoute,
  EmployeesSettingsRoute: EmployeesSettingsRoute,
  EmployeesTimesheetsRoute: EmployeesTimesheetsRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface FinanceRouteChildren {
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface InboxRouteChildren {
  InboxNotificationsRoute: typeof InboxNotificationsRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxNotificationsRoute: InboxNotificationsRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface OperationsRouteChildren {
  OperationsClientsRoute: typeof OperationsClientsRoute
  OperationsDeliverablesRoute: typeof OperationsDeliverablesRoute
  OperationsWorkloadRoute: typeof OperationsWorkloadRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsClientsRoute: OperationsClientsRoute,
  OperationsDeliverablesRoute: OperationsDeliverablesRoute,
  OperationsWorkloadRoute: OperationsWorkloadRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsEmployeesRoute: typeof ReportsEmployeesRoute
  ReportsFinanceRoute: typeof ReportsFinanceRoute
  ReportsLeadsRoute: typeof ReportsLeadsRoute
  ReportsProjectsRoute: typeof ReportsProjectsRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsEmployeesRoute: ReportsEmployeesRoute,
  ReportsFinanceRoute: ReportsFinanceRoute,
  ReportsLeadsRoute: ReportsLeadsRoute,
  ReportsProjectsRoute: ReportsProjectsRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SettingsRouteChildren {
  SettingsClientPackagesRoute: typeof SettingsClientPackagesRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsWorkflowsRoute: typeof SettingsWorkflowsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsClientPackagesRoute: SettingsClientPackagesRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsWorkflowsRoute: SettingsWorkflowsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TasksRouteChildren {
  TasksBoardRoute: typeof TasksBoardRoute
  TasksCalendarRoute: typeof TasksCalendarRoute
  TasksListRoute: typeof TasksListRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksBoardRoute: TasksBoardRoute,
  TasksCalendarRoute: TasksCalendarRoute,
  TasksListRoute: TasksListRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  ClientsRoute: ClientsRouteWithChildren,
  EmployeesRoute: EmployeesRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InboxRoute: InboxRouteWithChildren,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
